# backend/ml/models/__init__.py
"""
LumindAd Enterprise · backend/ml/models
Trained model binaries — generated by generate_models.py

Files
──────
LumindAd_MLP.keras
  Keras Sequential · input(20) → Dense 128→64→32 → sigmoid(1)
  Accuracy 90.3% · AUC 99.3% · 13,825 params
  Task: churn · click quality · ROAS quality

LumindAd_LSTM.keras
  Keras Sequential · input(10,20) → LSTM 64 → LSTM 32 → Dense 16 → sigmoid(1)
  Accuracy 98.0% · AUC 99.7% · 34,721 params
  Task: churn (temporal sequence)

LumindAd_CNN1D.keras
  Keras Sequential · input(10,20) → Conv1D 64 → Conv1D 32 → Dense 32 → sigmoid(1)
  Accuracy 98.5% · AUC 99.9% · 11,169 params
  Task: churn (local pattern detection)

LumindAd_Autoencoder.keras
  Keras Model · input(20) → bottleneck(4) → output(20)
  MSE 0.279 · MAE 0.471 · 1,032 params
  Task: anomaly detection (reconstruction error scoring)

best_ml_XGBoost.pkl
  XGBClassifier · n_estimators=200 · max_depth=6 · lr=0.05
  AUC 98.9% · primary churn model (40% ensemble weight)

scaler_robust.pkl
  RobustScaler · fitted on 1,000 synthetic Telecom X samples
  n_features=20 · IQR-based clipping

Regenerate
───────────
  cd backend && python ml/models/generate_models.py

Author : Elizabeth Díaz Familia
         AI Data Scientist · Sustainable Intelligence & BI
"""
