/**
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *  LumindAd · utils/registerSW.ts
 *  src/utils/registerSW.ts
 *
 *  Purpose
 *   PWA Service Worker registration, update lifecycle management,
 *   and online/offline event broadcasting. Called once from
 *   main.tsx after ReactDOM.createRoot().render().
 *
 *  Lifecycle
 *   1. registerSW() — called on app boot (production only)
 *   2. SW installs → caches static assets (Workbox precache)
 *   3. App starts via cached assets → offline mode available
 *   4. Every 60s → registration.update() checks for new SW
 *   5. New SW found → "installed" state → dispatches
 *      'lumindad:sw-update-available' CustomEvent
 *   6. UpdateBanner component (in AppLayout) listens for that
 *      event and shows "New version available — click to refresh"
 *   7. User clicks Refresh → postMessage({type:'SKIP_WAITING'})
 *      → new SW activates → page reloads
 *
 *  Custom events dispatched on window
 *   'lumindad:sw-update-available' — new version waiting
 *   'lumindad:sw-installed'        — first install complete
 *   'lumindad:online'              — browser regained network
 *   'lumindad:offline'             — browser lost network
 *
 *  Exports
 *   registerSW()         — main entry point (main.tsx)
 *   unregisterSW()       — for logout / settings reset
 *   skipWaiting()        — trigger pending SW activation
 *   onSWMessage(cb)      — subscribe to messages from the SW
 *   isOnline()           — current online state
 *
 *  SW path
 *   '/sw.js' — generated by vite-plugin-pwa (Workbox)
 *   updateViaCache:'none' forces network re-check of the SW
 *   script itself (bypasses HTTP cache for the SW file).
 *
 *  Author : Elizabeth Díaz Familia
 *           AI Data Scientist · Sustainable Intelligence & BI
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 */

// ─── Internal state ───────────────────────────────────────────────────────────

let _registration: ServiceWorkerRegistration | null = null;
let _updateInterval: ReturnType<typeof setInterval> | null = null;

// ─── Custom event helpers ─────────────────────────────────────────────────────

function dispatch(name: string, detail?: unknown): void {
  window.dispatchEvent(new CustomEvent(name, { detail }));
}

// ═══════════════════════════════════════════════════════════════
// REGISTER SERVICE WORKER
// ═══════════════════════════════════════════════════════════════

/**
 * Register the LumindAd Service Worker.
 * Called once from main.tsx — safe to call multiple times.
 *
 * Only runs in production (`import.meta.env.PROD`).
 * In development, logs a message and returns early so that
 * Vite's HMR is not blocked by SW caching.
 *
 * @example
 * // main.tsx
 * import { registerSW } from './utils/registerSW';
 * registerSW();
 */
export function registerSW(): void {
  // ── Dev mode guard ────────────────────────────────────────────────────────
  if (!import.meta.env.PROD) {
    console.info(
      '[LumindAd SW] Development mode — Service Worker skipped. ' +
      'SW is active in production builds only.',
    );
    return;
  }

  // ── Browser support guard ─────────────────────────────────────────────────
  if (!('serviceWorker' in navigator)) {
    console.warn('[LumindAd SW] Service Workers not supported in this browser.');
    return;
  }

  // ── Register after full page load — avoids competing with initial paint ───
  window.addEventListener('load', () => {
    _doRegister();
  });

  // ── Online / offline events ───────────────────────────────────────────────
  window.addEventListener('online',  () => dispatch('lumindad:online'));
  window.addEventListener('offline', () => dispatch('lumindad:offline'));
}

async function _doRegister(): Promise<void> {
  try {
    const reg = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
      // updateViaCache:'none' — always network-check the SW script,
      // bypasses HTTP cache so users always get the latest SW.
      updateViaCache: 'none',
    });

    _registration = reg;

    console.log('[LumindAd SW] ✅ Registered — scope:', reg.scope);

    // ── First install detection ────────────────────────────────────────────
    if (!navigator.serviceWorker.controller) {
      // This is the very first install — no existing controller.
      // The SW will activate on next navigation.
      reg.addEventListener('updatefound', () => {
        const sw = reg.installing;
        if (!sw) return;
        sw.addEventListener('statechange', () => {
          if (sw.state === 'activated') {
            console.log('[LumindAd SW] 🆕 First install complete.');
            dispatch('lumindad:sw-installed');
          }
        });
      });
    }

    // ── Update detection ──────────────────────────────────────────────────
    reg.addEventListener('updatefound', () => {
      const newSW = reg.installing;
      if (!newSW) return;

      newSW.addEventListener('statechange', () => {
        // New SW has installed and there's already an active controller
        // → a previous version is running, this is an update
        if (newSW.state === 'installed' && navigator.serviceWorker.controller) {
          console.log('[LumindAd SW] 🔄 New version available — waiting to activate.');
          dispatch('lumindad:sw-update-available', { registration: reg });
        }
      });
    });

    // ── Periodic update check ─────────────────────────────────────────────
    // Checks every 60 seconds while the tab is active.
    // Silent fail when offline (network error on update() is expected).
    _updateInterval = setInterval(() => {
      reg.update().catch(() => {
        // User is likely offline — not an error
      });
    }, 60_000);

    // ── SW message bridge ─────────────────────────────────────────────────
    // Forward messages from the SW to window listeners.
    navigator.serviceWorker.addEventListener('message', (e) => {
      dispatch('lumindad:sw-message', e.data);
    });

  } catch (error) {
    console.error('[LumindAd SW] ❌ Registration failed:', error);
  }
}

// ═══════════════════════════════════════════════════════════════
// SKIP WAITING — activate pending SW immediately
// ═══════════════════════════════════════════════════════════════

/**
 * Tell the waiting Service Worker to skip its waiting phase and
 * activate immediately. After it activates, reloads the page to
 * load the new assets.
 *
 * Called by the UpdateBanner component when the user clicks
 * "Refresh to update".
 *
 * @example
 * // In AppLayout's update banner:
 * <button onClick={() => skipWaiting()}>Refresh to update</button>
 */
export function skipWaiting(): void {
  if (!_registration) return;

  const waitingSW = _registration.waiting;
  if (waitingSW) {
    waitingSW.postMessage({ type: 'SKIP_WAITING' });
    // Listen for the new SW to take control, then reload
    navigator.serviceWorker.addEventListener('controllerchange', () => {
      window.location.reload();
    }, { once: true });
  }
}

// ═══════════════════════════════════════════════════════════════
// UNREGISTER — for logout / PWA reset
// ═══════════════════════════════════════════════════════════════

/**
 * Unregister all Service Workers for this origin.
 * Clears the periodic update interval.
 * Used by the Settings "Reset PWA" action.
 *
 * @example
 * await unregisterSW();
 * console.log('SW unregistered — hard refresh required');
 */
export async function unregisterSW(): Promise<void> {
  if (_updateInterval) {
    clearInterval(_updateInterval);
    _updateInterval = null;
  }

  if (!('serviceWorker' in navigator)) return;

  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(registrations.map(r => r.unregister()));
    _registration = null;
    console.log('[LumindAd SW] 🧹 All Service Workers unregistered.');
  } catch (error) {
    console.error('[LumindAd SW] Failed to unregister:', error);
  }
}

// ═══════════════════════════════════════════════════════════════
// SW MESSAGE BRIDGE
// ═══════════════════════════════════════════════════════════════

/**
 * Subscribe to messages broadcast by the Service Worker.
 * Returns an unsubscribe function.
 *
 * @example
 * const unsub = onSWMessage((data) => {
 *   if (data.type === 'CACHE_UPDATED') refetchDashboard();
 * });
 * // Later:
 * unsub();
 */
export function onSWMessage(
  callback: (data: unknown) => void,
): () => void {
  function handler(e: Event) {
    callback((e as CustomEvent).detail);
  }
  window.addEventListener('lumindad:sw-message', handler);
  return () => window.removeEventListener('lumindad:sw-message', handler);
}

// ═══════════════════════════════════════════════════════════════
// ONLINE STATE
// ═══════════════════════════════════════════════════════════════

/**
 * Current online/offline state.
 * Reactive: subscribe to 'lumindad:online' / 'lumindad:offline'
 * CustomEvents on window for updates.
 *
 * @example
 * if (!isOnline()) showOfflineBanner();
 */
export function isOnline(): boolean {
  return typeof navigator !== 'undefined' ? navigator.onLine : true;
}

// ═══════════════════════════════════════════════════════════════
// CURRENT REGISTRATION (for advanced consumers)
// ═══════════════════════════════════════════════════════════════

/**
 * Access the active ServiceWorkerRegistration (if registered).
 * Null before registerSW() completes or in development.
 *
 * @example
 * const reg = getRegistration();
 * reg?.showNotification('LumindAd', { body: 'Processing complete' });
 */
export function getRegistration(): ServiceWorkerRegistration | null {
  return _registration;
}
